name: Send Telegram Notification on Release

on:
  release:
    types: [published]

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 نسخه جدید *WidgetCore* منتشر شد !
            🏷 *نسخه :* `${{ github.event.release.tag_name }}`
            📝 *تغییرات نسخه :*
            ${{ github.event.release.body }}
            
            🔗 [مشاهده و دانلود نسخه جدید](${{ github.event.release.html_url }})
            🌐 [مشاهده مستندات آنلاین](https://docs.widgetcore.ir/changelog/)